---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность играть с другим пользователем, другом или ботом
  - На сайте должна быть предоставлена возможность двум игрокам соревноваться друг с другом в решении задач и видеть написание кода друг у друга.
  - Сайт должен иметь мобильную версию
  - 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Важно, чтобы сайт мог обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - 
implisit:
  - Пользователь не должен иметь возможность редактировать данные на сайте
  - 

  
