---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте по имеющемуся логину и паролю, а так же выйти из своего аккаунта.
  - Пользователь должен иметь возможность играть с другим пользователем, другом или ботом
  - На сайте должна быть предоставлена возможность двум игрокам соревноваться друг с другом в решении задач и видеть написание кода друг у друга
  - на главной странице авторизованного пользователя должны быть шапка, подвал и следующие блоки:
    таблица игроков с данными об игре, создание игры, общий чат и игроки онлайн
  - Сайт должен быть на английском языке и иметь возможность прочитать задание игры на русском
  - В шапке сайта в левом углу должен быть логотип сайта, а в правом - количество игроков онлайн, значок приглашений и кнопка входа в личный профиль
  - На кнопке входа в личный профиль должны отображаться имя пользователя, количество заработанных баллов, место в общем рейтинге и аватар пользователя
    (если его нет, то должен отображаться заменяющий его значок)
  - В личном профиле должны быть следующие разделы: My Profile, Settings, Users rating, Tasks, Tournaments
  - При входе в My profile должны отображаться личные данные пользователя (логотип, выбранный язык программирования, время присоединения к проекту,
    общая статистика активности, данные о пройденных играх и их общее количество
  - В настройках пользователь должен иметь возможность изменить имя, язык программирования, клан и режим и уровень громкости. Так же должны быть
    ссылки для связки аккаунта с Github и Discord
  - В Users rating должна отображаться таблица рейтинга игроков с постраничным выводом и возможностью менять количество строк на странице, а так же
    с возможностью перехода в начало и конец списка. Должно отображаться общее количество игроков. Рейтинг должен иметь сортировку за неделю, месяц и все время
    В таблице должно быть имя игрока, номер места в рейтинге и ссылка на профиль на Github игрока, если он привязан. Должна быть фильтрация по убыванию
    и возврастанию у значений: Rank, Reting, Games played, Joined. Должен быть отдельный фильтр по играм с ботом.
  - В разделе Tasks должна отображаться таблица со всеми созданными пользователями заданиями и данными о пользователе и задании. 
    Пользователь должен иметь возможность создать новое задание для игры, а так же открыть для просмотра уже созданное. 
  - В разделе Tournaments должна отображаться таблица турниров с названием турнира, его типом, уровнем сложности, статусом (закончился, в процессе
    или можно присоединиться) и датой начала. Должна быть ссылка на страницу, где можно прочитать подробное его описание и присоединиться к турниру,
    а так же участвовать в общем чате турнира
  - На сайте должна быть ссылка SourceCode, которая приводит на страницу проекта в Github, где можно завести багрепорт или предложить какую-либо
    новую функциональность, а так же посмотреть или проверить то, что уже было заведено пользователями
  - Должны быть ссылки на главную страницу сайта Hexlet, а так же ссылки на присоединение к общему чату игроков в телеграмме и дикорде.
  - На главной странице должны быть 3 вкладки: Lobby, Tournaments, History. В них должна отображаться соответствующая информация об играх, турнирах и участниках
  - Доступ к просмотру подробной информации о прошедших играх и турнирах, а так же тестрирование собственных заданий должны быть только для премиум подписчиков.
  - В таблице игроков должны отображаться 
  - Сайт должен иметь мобильную версию
  - При создании игры, должны быть 4 уровня сложности; выбор игры с другим пользователем, с другом или ботом; установка лимита времени на игру,
    а так же выбор задания: любого из выпадающего списка, рандомный выбор и по тегам
  - В игре должна быть кнопка-гид помощи, где будет рассказаны и показаны все поля, обозначения и кнопки. При первом запуске игры гид должен появиться автоматически.
    Должен отображаться таймер убывания времени игры, имена игроков и счет (если игра повторяется неоднократно). Должна быть кнопка запуска кода после его написания,
    кнопка сброса написанного кода, а так же кнопка "сдаться" до окончания времени игры, нажатие на которую приравнивается к проигрышу. В момент игры должен быть
    открыт общий чат. Когда игра закончена, должно появиться модальное окно с музыкой и соответствующим описанием выигрыш это или проигрыш. После окончания игры
    должна быть возможность сыграть эту же игру заново или вернуться на главную страницу
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Важно, чтобы сайт мог обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - 
implisit:
  - Пользователь не должен иметь возможность редактировать данные (кроме личных настроек) на сайте
  - 

  
